version: '3.8'
services:
  frontend:
    image: simmondobber/lombokerfrontend
    build: ./Frontend
  backend:
    image: simmondobber/lombokerbackend
    build: ./Backend
  nginx:
    image: simmondobber/lombokernginx
    build: ./Nginx
    ports:
      - "80:80"

