export enum AnnotationDataTO {
    GETTER = "GETTER",
    SETTER = "SETTER",
    NO_ARGS_CONSTRUCTOR = "NO_ARGS_CONSTRUCTOR",
    ALL_ARGS_CONSTRUCTOR = "ALL_ARGS_CONSTRUCTOR",
    BUILDER = "BUILDER",
    BUILDER_TO_BUILDER = "BUILDER_TO_BUILDER",
    SUPER_BUILDER = "SUPER_BUILDER",
    SUPER_BUILDER_TO_BUILDER = "SUPER_BUILDER_TO_BUILDER",
    TO_STRING = "TO_STRING",
    TO_STRING_CALL_SUPER = "TO_STRING_CALL_SUPER",
    EQUALS_AND_HASH_CODE = "EQUALS_AND_HASH_CODE"
}
